# Generated by Django 3.0 on 2021-02-23 09:02

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('todo_from', models.IntegerField(verbose_name='todo_from')),
                ('todo_to', models.IntegerField(verbose_name='todo_to')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
